# Generated by Django 3.0.8 on 2020-07-20 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('name', models.CharField(max_length=120, verbose_name='Event Name')),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Base_stats', models.CharField(max_length=60)),
                ('Height', models.IntegerField()),
                ('weight', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Event',
        ),
    ]
